// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9TmU19QlzLFDI9_0LWXbO-QkuG1JjiF8',
    appId: '1:507101099716:web:ca45140526ae70bc7c7b91',
    messagingSenderId: '507101099716',
    projectId: 'quiz-app-d9cca',
    authDomain: 'quiz-app-d9cca.firebaseapp.com',
    storageBucket: 'quiz-app-d9cca.firebasestorage.app',
    measurementId: 'G-31C8YSDZ6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMX9UhB5lnQg2QKErvigjSeoa4xQVzvOw',
    appId: '1:507101099716:android:53934034fdd913ba7c7b91',
    messagingSenderId: '507101099716',
    projectId: 'quiz-app-d9cca',
    storageBucket: 'quiz-app-d9cca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxHO-3pKY1OkwzjbwCUk_RcNc3ESbWTrk',
    appId: '1:507101099716:ios:2935db27621f3b9d7c7b91',
    messagingSenderId: '507101099716',
    projectId: 'quiz-app-d9cca',
    storageBucket: 'quiz-app-d9cca.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxHO-3pKY1OkwzjbwCUk_RcNc3ESbWTrk',
    appId: '1:507101099716:ios:2935db27621f3b9d7c7b91',
    messagingSenderId: '507101099716',
    projectId: 'quiz-app-d9cca',
    storageBucket: 'quiz-app-d9cca.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9TmU19QlzLFDI9_0LWXbO-QkuG1JjiF8',
    appId: '1:507101099716:web:33149aa63c63fd6c7c7b91',
    messagingSenderId: '507101099716',
    projectId: 'quiz-app-d9cca',
    authDomain: 'quiz-app-d9cca.firebaseapp.com',
    storageBucket: 'quiz-app-d9cca.firebasestorage.app',
    measurementId: 'G-JVSZ7ZKW76',
  );
}
