// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVssEV716mvMetbO58wKrFBRtW0MhNvbE',
    appId: '1:990083917370:web:18ddc6f26c6231449fb703',
    messagingSenderId: '990083917370',
    projectId: 'my-quizqpp-1',
    authDomain: 'my-quizqpp-1.firebaseapp.com',
    storageBucket: 'my-quizqpp-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuHuLOK7-sc0leXuDIxuDh7V0Leh71URQ',
    appId: '1:990083917370:android:de7af52ede6869aa9fb703',
    messagingSenderId: '990083917370',
    projectId: 'my-quizqpp-1',
    storageBucket: 'my-quizqpp-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0GWcAlcKmqjShthy682DgRrGFxo14tzc',
    appId: '1:990083917370:ios:9039b9eabede23b89fb703',
    messagingSenderId: '990083917370',
    projectId: 'my-quizqpp-1',
    storageBucket: 'my-quizqpp-1.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0GWcAlcKmqjShthy682DgRrGFxo14tzc',
    appId: '1:990083917370:ios:9039b9eabede23b89fb703',
    messagingSenderId: '990083917370',
    projectId: 'my-quizqpp-1',
    storageBucket: 'my-quizqpp-1.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVssEV716mvMetbO58wKrFBRtW0MhNvbE',
    appId: '1:990083917370:web:0e7a7dbf7a0d1df29fb703',
    messagingSenderId: '990083917370',
    projectId: 'my-quizqpp-1',
    authDomain: 'my-quizqpp-1.firebaseapp.com',
    storageBucket: 'my-quizqpp-1.firebasestorage.app',
  );
}
